"""Type stubs for skytrade.engine (Rust extension module)."""

from typing import Optional

class SkyRequest:
    method: str
    path: str
    params: dict[str, str]
    query: str
    headers: dict[str, str]
    body: bytes
    query_params: dict[str, str]
    def text(self) -> str: ...
    def json(self) -> dict: ...

class SkyResponse:
    body: object
    status_code: int
    content_type: Optional[str]
    headers: dict[str, str]
    def __init__(
        self,
        body: object,
        status_code: int = 200,
        content_type: Optional[str] = None,
        headers: Optional[dict[str, str]] = None,
    ) -> None: ...

class SkyWebSocket:
    def recv(self) -> Optional[str]: ...
    def send(self, msg: str) -> None: ...
    def close(self) -> None: ...

class SkyApp:
    def __init__(self) -> None: ...
    def get(self, path: str, handler: object, gil: bool = False) -> None: ...
    def post(self, path: str, handler: object, gil: bool = False) -> None: ...
    def put(self, path: str, handler: object, gil: bool = False) -> None: ...
    def delete(self, path: str, handler: object, gil: bool = False) -> None: ...
    def route(self, method: str, path: str, handler: object, gil: bool = False) -> None: ...
    def before_request(self, handler: object) -> None: ...
    def after_request(self, handler: object) -> None: ...
    def fallback(self, handler: object) -> None: ...
    def websocket(self, path: str, handler: object) -> None: ...
    def static_dir(self, prefix: str, directory: str) -> None: ...
    def run(
        self,
        host: Optional[str] = None,
        port: Optional[int] = None,
        workers: Optional[int] = None,
        mode: Optional[str] = None,
    ) -> None: ...
